### ISSUE TITLE
Unknown host 'databridge.eionet.europa.eu'.

### ISSUE THREAD

**Issue by warton** [eea/eprtr-lcp-dataflow#1]
Hi guys from this cool project.

I'm working on implementation of reporting process for SK and after I tried your xquery validations, it didn't work.
Issue seems to be in domain you are using in main script to fetch some data. Here is my result:

```
C:\www\nrz-admin/bin/basex/bin/basex.bat -bsource_url=C:\www\nrz-admin\storage\app\/eprtr/eprtr-1601019227.xml C:\www\nrz-admin\storage\app\eprtr\eprtr-lcp-main.xq > C:\www\nrz-admin\storage\app\eprtr\eprtr-1601019227.html
Stopped at C:/www/nrz-admin/storage/app/eprtr/eprtr-lcp-main.xq, 45/39:
[experr:HC0001] Unknown host 'databridge.eionet.europa.eu'.
```

Could you please help me solving this issue? Thanks. Miro
https://github.com/eea/eprtr-lcp-dataflow/blob/493f33dea071fbbd54b7655519fbb6e62f8af576/xquery/eprtr-lcp-main.xq#L36

**Comment by laszlocseh** [comment]
Hi Miroslav, 'databridge.eionet.europa.eu' is not public, holds some private data and cannot be accessed

As a workaround you can change the location to a relative path ex. './folder1'. However some validations may be skipped, because of the missing data from 'databridge.eionet.europa.eu'

**Comment by warton** [comment]
Cool, it seems to be working now.

Thanks.
